// Access the element with the ID "guessWord"
const guessWordElement = document.getElementById("guessWord");
const categoryElement = document.getElementById("category");

let category_ID = 0;
let NUM_CATEGORIES = 2;

let CATEGORIES = ["Geeky", "Kids Shows"];

// Access the button with the ID "next"
const nextButton = document.getElementById("next");

const geeky = [
    "The One Ring",
    "Mount Doom",
    "The Shire",
    "Fellowship of the Ring",
    "Rivendell",
    "Gandalf the Grey",
    "Gollum’s obsession",
    "Sauron’s Eye",
    "Isengard",
    "Mordor’s darkness",
    "Aragorn, son of Arathorn",
    "Frodo Baggins",
    "Samwise Gamgee",
    "Legolas the Elf",
    "Gimli the Dwarf",
    "Boromir’s sacrifice",
    "Galadriel’s mirror",
    "Lothlórien",
    "The Mines of Moria",
    "The Anduin River",
    "The Green Dragon Inn",
    "The Argonath",
    "The Paths of the Dead",
    "The Black Gate",
    "The Palantír",
    "Rohan’s riders",
    "Theoden King",
    "Eowyn’s bravery",
    "Saruman’s treachery",
    "Ents of Fangorn",
    "Treebeard",
    "Shelob’s lair",
    "The Dead Marshes",
    "The Elven blade, Sting",
    "The Nazgûl",
    "The Horn of Helm Hammerhand",
    "The White City, Gondor",
    "Minas Tirith",
    "The Battle of Helm’s Deep",
    "The Siege of Gondor",
    "The Black Riders",
    "The Gray Havens",
    "Elrond Half-elven",
    "The Last Alliance",
    "The Ringwraiths",
    "The Red Book of Westmarch",
    "The Eagle’s flight",
    "The Battle of the Five Armies",
    "The White Council",
    "The Palantir of Orthanc",
    "Gildor Inglorion",
    "The Golden Wood",
    "The Fellowship’s oath",
    "Glorfindel’s valor",
    "Eomer’s charge",
    "The Light of Eärendil",
    "The Hornburg",
    "Osgiliath",
    "Grishnákh’s betrayal",
    "Gollum’s riddles",
    "The Gates of Moria",
    "Minas Morgul",
    "Barad-dûr",
    "The Two Towers",
    "The Shire’s peace",
    "The Broken Sword of Elendil",
    "Pippin Took",
    "Merry Brandybuck",
    "Mount Caradhras",
    "The Mûmakil",
    "Galadriel’s gifts",
    "The Mirror of Galadriel",
    "The Fords of Isen",
    "The Fall of Numenor",
    "The Army of the Dead",
    "The Battle of Pelennor Fields",
    "The Black Gate of Mordor",
    "The Elessar Stone",
    "The Scouring of the Shire",
    "Faramir’s wisdom",
    "Denethor’s madness",
    "The Steward of Gondor",
    "The Ring’s corruption",
    "The Stewards of Gondor",
    "The Beacons of Gondor",
    "Gollum’s dual nature",
    "The Fellowship’s journey",
    "The Siege of Minas Tirith",
    "The Paths of the King",
    "The Pillars of the Kings",
    "Arwen Evenstar",
    "The Light of Galadriel",
    "The Gates of Gondor",
    "The Tower of Cirith Ungol",
    "The Witch-king of Angmar",
    "The White Tree of Gondor",
    "The Last Homely House",
    "The Redhorn Pass",
    "The Ring’s power",
    "The Age of Men",
    "The Force",
    "Lightsaber",
    "Darth Vader",
    "The Death Star",
    "Jedi Knight",
    "Sith Lord",
    "The Millennium Falcon",
    "The Empire Strikes Back",
    "The Rebel Alliance",
    "The Dark Side",
    "The Galactic Senate",
    "Tatooine",
    "Yoda’s wisdom",
    "The Clone Wars",
    "The Mandalorian",
    "R2-D2",
    "C-3PO",
    "Princess Leia",
    "Han Solo",
    "Chewbacca",
    "Obi-Wan Kenobi",
    "Anakin Skywalker",
    "The Jedi Council",
    "The Phantom Menace",
    "The Force Awakens",
    "The Last Jedi",
    "Return of the Jedi",
    "The Rise of Skywalker",
    "Kylo Ren",
    "The First Order",
    "Boba Fett",
    "The Mandalorian armor",
    "Darth Maul’s double-bladed lightsaber",
    "The Jedi Temple",
    "The Sith Code",
    "The Rebel Fleet",
    "The TIE fighter",
    "The X-wing starfighter",
    "Tatooine’s twin suns",
    "The podrace",
    "Jabba the Hutt",
    "The Ewoks",
    "The Hoth Battle",
    "The Sand People",
    "The Wookiee life debt",
    "The Ewok Village",
    "The Millennium Falcon’s hyperdrive",
    "The Death Star trench run",
    "Luke Skywalker",
    "The Dark Lord of the Sith",
    "Qui-Gon Jinn",
    "Mace Windu",
    "Ahsoka Tano",
    "Darth Sidious",
    "Count Dooku",
    "The Battle of Endor",
    "The Battle of Coruscant",
    "The Droid Army",
    "General Grievous",
    "The Mandalorian Darksaber",
    "The Galactic Empire",
    "The Emperor’s Throne Room",
    "The Force choke",
    "The Imperial March",
    "The Jedi Code",
    "The Tatooine Dune Sea",
    "Podracing on Malastare",
    "The Womp rat",
    "The Kessel Run",
    "The Rebel’s Strike Fighter",
    "The Force lightning",
    "The Togruta species",
    "The Star Destroyer",
    "The HoloNet",
    "Jango Fett",
    "The Battle of Yavin",
    "The Star Wars cantina",
    "The Sith Temple",
    "The Kyber crystals",
    "The Star Wars Holiday Special",
    "The Togruta species",
    "The Shadow Collective",
    "The Outer Rim Territories",
    "The Womp rat",
    "Qui-Gon Jinn’s last words",
    "The Republic Navy",
    "The Yavin 4 base",
    "The Rebel blockade runner",
        "The Avatar",
        "Aang’s Airbending",
        "Water Tribe",
        "Earth Kingdom",
        "Fire Nation",
        "The Southern Air Temple",
        "The Northern Water Tribe",
        "Katara’s Waterbending",
        "Toph’s Earthbending",
        "Zuko’s redemption",
        "The Firebending Masters",
        "The Last Airbender",
        "The Lion Turtle",
        "The Avatar State",
        "Ba Sing Se",
        "Sozin’s Comet",
        "Roku’s spirit",
        "Sokka’s boomerang",
        "The White Lotus",
        "Iroh’s tea",
        "The Firelord",
        "The Spirit World",
        "Kyoshi Warriors",
        "The Southern Water Tribe",
        "The Earth Kingdom’s walls",
        "Aang’s flying bison, Appa",
        "Momo the flying lemur",
        "The Fire Nation Royal Family",
        "Azula’s lightning",
        "Toph Beifong’s metalbending",
        "Katara’s healing water",
        "The Great Divide",
        "Zuko’s scar",
        "The Day of Black Sun",
        "Toph’s “I’m the greatest earthbender in the world”",
        "The Earth King",
        "Sokka’s sword",
        "Suki and the Kyoshi Warriors",
        "Avatar Aang’s tattoos",
        "The Ember Island Players",
        "The Fire Nation’s ambition",
        "The Earthbender’s training",
        "The Northern Air Temple",
        "The Southern Air Temple",
        "Sokka’s “meat and sarcasm”",
        "The Great Sage",
        "Iroh’s wisdom",
        "Zuko’s struggle",
        "The Royal Firebending Academy",
        "The Fire Nation capital",
        "The Secret Tunnel Song",
        "The Blue Spirit",
        "Avatar Roku’s past",
        "The Sea Prisons",
        "Sokka’s leadership",
        "The Yuyan Archers",
        "The Fire Nation soldiers",
        "Katara’s necklace",
        "Aang’s quest for knowledge",
        "The Firebending Masters’ cave",
        "The Earth Kingdom’s culture",
        "The Painted Lady spirit",
        "The Fire Nation’s warships",
        "The Swamp spirit",
        "The Southern Air Temple’s destruction",
        "Toph’s “You’re not the boss of me!”",
        "The Waterbending scroll",
        "The Fire Nation’s war machine",
        "The Earth Kingdom’s underground",
        "The Fire Nation’s prisons",
        "The Crystal Catacombs",
        "The Spirit Oasis",
        "The Southern Raiders",
        "The Fire Nation invasion",
        "The Waterbender’s training",
        "The Avatar’s past lives",
        "The Fire Nation’s occupation",
        "The Earth King’s palace",
        "The Final Agni Kai",
        "The Siege of the North",
        "The Serpent’s Pass",
        "The Fire Nation’s fleet of ships",
        "The Bounty Hunter’s team",
        "The Fire Nation’s generals",
        "The Earth Kingdom’s armies",
        "The Light of the Spirit",
        "The Final Battle of the Four Nations",
        "Aang’s quest for peace",
        "The Fire Lord’s throne room",
        "The Kyoshi Island warriors",
        "The Earthbending teacher",
        "The Water Tribe’s elders",
        "The Avatar’s final task",
        "Zuko’s swordsmanship",
        "The Fire Nation’s downfall",
        "The Capitol",
        "District 12",
        "Katniss Everdeen",
        "Peeta Mellark",
        "Primrose Everdeen",
        "The Hunger Games arena",
        "The Mockingjay",
        "District 13",
        "The Gamesmaker",
        "President Snow",
        "The Capitol’s control",
        "The Reaping",
        "The Cornucopia",
        "Haymitch Abernathy",
        "The Girl on Fire",
        "Cinna’s design",
        "The Districts",
        "The Seam",
        "The Capitol’s luxury",
        "The Tracker Jackers",
        "The District 12 Victor",
        "Rue’s sacrifice",
        "The Hunger Games motto",
        "The Avox punishment",
        "The District 11 rebellion",
        "The Hunger Games rebellion",
        "The Mockingjay pin",
        "The Capitol’s propaganda",
        "The Quell",
        "The Capitol’s peacekeepers",
        "The Capitol’s technology",
        "The uprising",
        "The Second Rebellion",
        "The Mockingjay symbol",
        "The Hunger Games victors",
        "The Quarter Quell",
        "The arena’s dangers",
        "The bloodbath",
        "The career tributes",
        "The hovercraft",
        "The Capitol’s wealth",
        "The District 13 underground",
        "The Capitol’s fashion",
        "The Mockingjay revolution",
        "The rebellion’s strategy",
        "The Capitol’s manipulation",
        "The victors’ tour",
        "The 75th Hunger Games",
        "The Hunger Games arena designs",
        "The Capitol’s glitz and glamour",
        "The Capitol’s cruelty",
        "The District 13 conspiracy",
        "The District 4 tribute",
        "The Katniss effect",
        "The Mockingjay’s message",
        "The rebellion’s tactics",
        "The rebellion’s leadership",
        "The Capitol’s punishment",
        "The Capitol’s social hierarchy",
        "The peacekeeper’s control",
        "The Capitol’s military",
        "The Capitol’s control of food",
        "The District 2 tributes",
        "The District 1 tributes",
        "The District 3 tributes",
        "The District 10 tributes",
        "The District 9 tributes",
        "The District 8 tributes",
        "The District 7 tributes",
        "The District 6 tributes",
        "The District 5 tributes",
        "The District 4 tributes",
        "The Capitol’s oppression",
        "The final rebellion battle",
        "The Capitol’s downfall",
        "The battle for freedom",
        "The power of the Mockingjay",
        "The Capitol’s brainwashing",
        "The training center",
        "The tribute parade",
        "The Mockingjay anthem",
        "The rebellion’s sacrifices",
        "The rebellion’s heroes",
        "The Capitol’s surveillance",
        "The arena’s challenges",
        "The Capitol’s control over the people",
        "The power of the districts",
        "The rebellion’s victory",
        "The strength of the tributes",
        "The rebellion’s leaders",
        "The Capitol’s manipulation of media",
        "The tributes’ struggle for survival",
        "The Capitol’s propaganda machine",
        "The Capitol’s use of fear",
        "The struggle for survival in the arena",
        "The power of Katniss’ spirit",
        "The rebellion’s moral dilemma",
        "The Hunger Games’ legacy",
        "The districts’ unity",
        "The Capitol’s manipulation of hunger",
        "The rebellion’s war strategy",
        "The Capitol’s division of wealth",
        "victors",
            "The Power Rangers",
            "Morphing Grid",
            "Mighty Morphin Power Rangers",
            "Zordon",
            "Alpha 5",
            "Rita Repulsa",
            "Lord Zedd",
            "The Dragonzord",
            "The Megazord",
            "Green Ranger",
            "Red Ranger",
            "Pink Ranger",
            "Blue Ranger",
            "Yellow Ranger",
            "Black Ranger",
            "White Ranger",
            "Tommy Oliver",
            "Jason Lee Scott",
            "Kimberly Ann Hart",
            "Zack Taylor",
            "Trini Kwan",
            "Billy Cranston",
            "Rita’s minions",
            "The Putty Patrol",
            "The Thunder Megazord",
            "The Zeo Crystal",
            "The Turbo Rangers",
            "The Space Rangers",
            "The Lightspeed Rescue Rangers",
            "Time Force Rangers",
            "Wild Force Rangers",
            "Ninja Storm Rangers",
            "S.P.D. Rangers",
            "Mystic Force Rangers",
            "Operation Overdrive Rangers",
            "Jungle Fury Rangers",
            "RPM Rangers",
            "Samurai Rangers",
            "Megaforce Rangers",
            "Super Megaforce Rangers",
            "Dino Charge Rangers",
            "Dino Super Charge Rangers",
            "Beast Morphers Rangers",
            "The Morphing Sequence",
            "The Command Center",
            "The Morphers",
            "The Power Coins",
            "The Power Blasters",
            "The Power Sword",
            "The Dragon Dagger",
            "The Saber-Tooth Tiger",
            "The Mastodon",
            "The Pterodactyl",
            "The Triceratops",
            "The Tyrannosaurus Rex",
            "The Falconzord",
            "The Titanus",
            "The Thunderzord",
            "The Rescue Zords",
            "The Delta Squad Megazord",
            "The Time Force Megazord",
            "The Overdrive Megazord",
            "The Jungle Pride Megazord",
            "The RPM Zords",
            "The Samurai Megazord",
            "The Ninja Megazord",
            "The Dino Megazord",
            "The Dino Thunder Zords",
            "The Megazord Battle",
            "The Morphing Grid connection",
            "The Ranger suits",
            "The Power Ranger helmets",
            "The Turbo Megazord",
            "The S.P.D. Megazord",
            "The Zords’ power",
            "The Zeo Megazord",
            "The Mystic Force Zords",
            "The Wild Force Zords",
            "The Black Dragon",
            "The Gold Zeo Ranger",
            "The Quantum Ranger",
            "The Red Space Ranger",
            "The Blue Time Force Ranger",
            "The Black Wild Force Ranger",
            "The Red Samurai Ranger",
            "The Yellow Ninja Storm Ranger",
            "The Blue RPM Ranger",
            "The Green Dino Thunder Ranger",
            "The Silver Ranger",
            "The White SPD Ranger",
            "The Pink Time Force Ranger",
            "The Gold Samurai Ranger",
            "The Pink SPD Ranger",
            "The Ranger powers",
            "The battle cry",
            "The Power Rangers movie",
            "The Morphing Grid power",
            "The Zord battles",
            "The Ranger Legacy",
            "The Super Sentai connection",
            "The Master Morpher",
            "The Ranger spirit",
            "The Power of teamwork",
            "The Ranger weapons",
            "The Pink Ranger’s Pterodactyl Zord",
            "The Red Ranger’s T-Rex Zord",
            "The Ranger’s fight against evil",
            "The Shogun Strike",
            "The Battleizer",
            "The Ranger’s powers across dimensions",
            "The Power Rangers franchise",
            "The Red Ranger’s leadership",
            "The villainous Rita Repulsa",
            "The rise of Lord Zedd",
            "The battle between good and evil",
            "The return of Tommy Oliver",
            "The ever-growing Ranger team",
            "The power of friendship",
            "The Protectors of Earth",
            "The Chronicles of Narnia",
            "Aslan",
            "Narnia",
                "Video Games",
                "Anime",
                "Marvel Cinematic Universe (MCU)",
                "DC Extended Universe (DCEU)",
                "Doctor Who",
                "Pokémon",
                "Minecraft",
                "Lord of the Rings (expanded universe)",
                "Harry Potter (spinoffs and Fantastic Beasts)",
                "Star Wars (expanded universe and TV series)",
                "The Witcher",
                "Dungeons & Dragons",
                "The Matrix",
                "Stranger Things",
                "Avatar: The Last Airbender",
                "Cyberpunk",
                "Ghostbusters",
                "Jurassic Park",
                "Transformers",
                "Battlestar Galactica",
                "Supernatural",
                "Blade Runner",
                "X-Files",
                "Final Fantasy",
                "Tolkien’s Silmarillion",
                "Gamer Lingo",
                "Comic Book Villains",
                "Steampunk",
                "Star Trek (movies & series)",
                "Halo",
                "Yu-Gi-Oh!",
                "Rick and Morty",
                "Marvel and DC Villains",
                "Mass Effect",
                "Ghost in the Shell",
                "Lord of the Rings Video Games",
                "World of Warcraft",
                "Walking Dead",
                "Dragon Age",
                "Firefly",
                "Kingdom Hearts",
                "Transformers (Generation 1, etc.)",
                "Power Rangers",
                "Teenage Mutant Ninja Turtles",
                "The Hunger Games",
                "Superhero Teams",
                "Cyberpunk 2077",
                "Tales from the Crypt",
                "The Umbrella Academy",
                "Godzilla and Kaiju Movies",
                "Naruto",
                "Dragon Ball Z",
                "One Piece",
                "Attack on Titan",
                "My Hero Academia",
                "Fullmetal Alchemist",
                "Death Note",
                "Neon Genesis Evangelion",
                "Demon Slayer",
                "Bleach",
                "Tokyo Ghoul",
                "Hunter x Hunter",
                "Sword Art Online",
                "One Punch Man",
                "JoJo’s Bizarre Adventure",
                "Fairy Tail",
                "Black Clover",
                "Naruto Uzumaki",
                "Goku",
                "Luffy",
                "Saitama",
                "Eren Yeager",
                "Izuku Midoriya",
                "Kagome Higurashi",
                "Inuyasha",
                "Yusuke Urameshi",
                "Naruto’s Rasengan",
                "Natsu Dragneel",
                "Sakura Haruno",
                "Kakashi Hatake",
                "Levi Ackerman",
                "Gintoki Sakata",
                "Kamina",
                "Rei Ayanami",
                "Shinji Ikari",
                "Akame ga Kill!",
                "Cowboy Bebop",
                "Trigun",
                "Samurai Champloo",
                "Haruhi Suzumiya",
                "Yu-Gi-Oh!",
                "Digimon",
                "Fairy Tail Guild",
                "Zoro",
                "Yuno Gasai",
                "Kamina’s sunglasses",
                "FMA’s Philosopher’s Stone",
                "Fruits Basket",
                "Dragon Ball Super",
                "Attack on Titan’s Titans",
                "Mikasa Ackerman",
                "Sailor Moon",
                "Neon Genesis’ Angels",
                "Code Geass",
                "Yu Yu Hakusho",
                "Mobile Suit Gundam",
                "Bleach’s Soul Reapers",
                "The Seven Deadly Sins",
                "Mob Psycho 100",
                "Black Lagoon",
                "Hellsing",
                "Trigun’s Vash the Stampede",
                "Fullmetal Alchemist: Brotherhood",
                "Naruto’s Ninja World",
                "JoJo’s Stand Powers",
                "Death Note’s Death God",
                "Hunter x Hunter’s Hunters Exam",
                "Elfen Lied",
                "Akira",
                "Tokyo Ghoul’s Kaneki",
                "Angel Beats",
                "Re:Zero",
                "Your Name",
                "Steins;Gate",
                "Noragami",
                "Psycho-Pass",
                "JoJo’s bizarre family",
                "Bleach’s Bankai",
                "Dragon Ball Z’s Super Saiyan",
                "Rurouni Kenshin",
                "Great Teacher Onizuka",
                "D.Gray-man",
                "Soul Eater",
                "Fooly Cooly",
                "Love Live!",
                "The Promised Neverland",
                "Madoka Magica",
                "A Silent Voice",
                "Attack on Titan’s Wall Maria",
                "Bunny Girl Senpai",
                "Blue Exorcist",
                "The Rising of the Shield Hero",
                "Fairy Tail’s Dragon Slayers",
                "The Ancient Magus’ Bride",
                "Fate/Stay Night",
                "Mob Psycho’s esper powers",
                "Mob Psycho’s Reigen",
                "Trigun’s destruction",
                "Hunter x Hunter’s Chimera Ant arc",
                "Fruits Basket’s zodiac curse",
                "No Game No Life",
                "Durarara!!",
                "One Punch Man’s Saitama vs. Boros",
                "My Hero Academia’s U.A. High School",
                "Attack on Titan’s Scout Regiment",
                "Black Clover’s Magic Knights",
                "One Piece’s Grand Line",
                "Naruto’s Chidori",
                "Sailor Moon’s transformation",
                "JoJo’s Phantom Blood",
                "Dragon Ball Z’s Kamehameha",
                "Tokyo Ghoul’s mask",
                "The Melancholy of Haruhi Suzumiya",
                "Spirited Away",
                "Naruto’s Shadow Clone Jutsu",
                "Inuyasha’s Tetsusaiga",
                "Fullmetal Alchemist’s State Alchemists",
                "Bleach’s Soul Society",
                "One Piece’s Devil Fruit powers",
                "The Titans",
                "Eren Yeager",
                "Mikasa Ackerman",
                "Armin Arlert",
                    "Star Wars: Episode IV - A New Hope",
                    "Star Wars: Episode V - The Empire Strikes Back",
                    "Star Wars: Episode VI - Return of the Jedi",
                    "Star Wars: Episode I - The Phantom Menace",
                    "Star Wars: Episode II - Attack of the Clones",
                    "Star Wars: Episode III - Revenge of the Sith",
                    "Star Wars: The Force Awakens",
                    "Star Wars: The Last Jedi",
                    "Star Wars: The Rise of Skywalker",
                    "Rogue One: A Star Wars Story",
                    "Solo: A Star Wars Story",
                        "Iron Man",
                        "The Incredible Hulk",
                        "Iron Man 2",
                        "Thor",
                        "Captain America: The First Avenger",
                        "The Avengers",
                        "Iron Man 3",
                        "Thor: The Dark World",
                        "Captain America: The Winter Soldier",
                        "Guardians of the Galaxy",
                        "Avengers: Age of Ultron",
                        "Ant-Man",
                        "Captain America: Civil War",
                        "Doctor Strange",
                        "Guardians of the Galaxy Vol. 2",
                        "Spider-Man: Homecoming",
                        "Thor: Ragnarok",
                        "Black Panther",
                        "Avengers: Infinity War",
                        "Ant-Man and The Wasp",
                        "Captain Marvel",
                        "Avengers: Endgame",
                        "Spider-Man: Far From Home",
                        "Black Widow",
                        "Shang-Chi and the Legend of the Ten Rings",
                        "Eternals",
                        "Spider-Man: No Way Home",
                        "Doctor Strange in the Multiverse of Madness",
                        "Thor: Love and Thunder",
                        "Black Panther: Wakanda Forever",
                        "Ant-Man and the Wasp: Quantumania",
                        "Guardians of the Galaxy Vol. 3",
                        "The Marvels",
  "Robert Downey Jr.",
  "Chris Hemsworth",
  "Chris Evans",
  "Scarlett Johansson",
  "Mark Ruffalo",
  "Tom Hiddleston",
  "Chris Pratt",
  "Zoe Saldana",
  "Dave Bautista",
  "Vin Diesel",
  "Bradley Cooper",
  "Samuel L. Jackson",
  "Tom Holland",
  "Chadwick Boseman",
  "Paul Rudd",
  "Benedict Cumberbatch",
  "Tessa Thompson",
  "Cate Blanchett",
  "Michael B. Jordan",
  "Benedict Wong",
  "Angela Bassett",
  "Florence Pugh",
  "Rene Russo",
  "Harrison Ford",
  "Olivia Colman",
    "Mark Hamill",
    "Harrison Ford",
    "Carrie Fisher",
    "Natalie Portman",
    "Ewan McGregor",
    "Liam Neeson",
    "Samuel L. Jackson",
    "Ian McDiarmid",
    "Hayden Christensen",
    "Daisy Ridley",
    "John Boyega",
    "Oscar Isaac",
    "Adam Driver",
    "Billy Dee Williams",
    "Peter Mayhew",
    "Anthony Daniels",
    "Kenny Baker",
    "Alec Guinness",
    "Gwendoline Christie",
    "Donald Glover",
    "Benicio del Toro",
    "Lupita Nyong'o",
    "Laura Dern",
    "Kelly Marie Tran",
    "Woody Harrelson",
    "Phoebe Waller-Bridge"
  ];
  

const kids_shows = [
        "Snow White",
        "Cinderella",
        "Aurora",
        "Ariel",
        "Belle",
        "Jasmine",
        "Pocahontas",
        "Mulan",
        "Tiana",
        "Rapunzel",
        "Merida",
        "Moana",
        "Anna",
        "Elsa",
        "Vanellope Von Schweetz",
        "Kida",
        "Eilonwy",
        "Wendy Darling",
        "Megara",
        "Lady",
        "Perdita",
        "Bianca Minola",
        "Lilo Pelekai",
        "Flora",
        "Fa Mulan",
        "Anastasia Tremaine",
        "Drizella Tremaine",
        "Aunt Cass",
        "Medusa",
        "Cheshire Cat",
        "Aunt Velma",
        "Marah",
        "Tiana’s Frog Prince",
        "Princess Atta",
        "Maid Marian",
        "Duchess",
        "Mother Gothel",
        "Queen Leah",
        "Lady Tremaine",
        "Sabrina",
        "Nala",
        "Zira",
        "Queen Elsa",
        "Kiara",
        "Simba",
        "Kovu",
        "Marie",
        "Cleo",
        "Maui",
        "Sven",
  "Snow White and the Seven Dwarfs",
  "Cinderella",
  "Sleeping Beauty",
  "The Little Mermaid",
  "Beauty and the Beast",
  "Aladdin",
  "Pocahontas",
  "Mulan",
  "The Princess and the Frog",
  "Tangled",
  "Brave",
  "Moana",
  "Frozen",
  "Frozen II",
  "The Lion King",
  "Mulan II",
  "The Little Mermaid II",
  "Cinderella II",
  "Cinderella III",
  "Aladdin and the King of Thieves",
  "The Return of Jafar",
  "Pocahontas II",
  "The Lion King II",
  "Tangled Ever After",
  "Frozen Fever",
  "Moana's Grand Adventure",
  "Wreck-It Ralph",
  "Zootopia",
  "Raya and the Last Dragon",
  "Tangled Before Ever After",
  "The Jungle Book",
  "Lady and the Tramp",
  "Sleeping Beauty: The Special Edition",
  "Beauty and the Beast: The Enchanted Christmas",
  "The Little Mermaid: Ariel's Beginning",
  "The Black Cauldron",
  "Atlantis: The Lost Empire",
  "Frozen",
  "Tarzan",
  "Peter Pan",
  "Alice in Wonderland",
  "101 Dalmatians",
  "Lady and the Tramp II",
  "The Many Adventures of Winnie the Pooh",
  "The Aristocats",
  "Lilo & Stitch",
  "The Sword in the Stone",
  "Toy Story",
  "A Bug's Life",
  "Toy Story 2",
  "Monsters, Inc.",
  "Finding Nemo",
  "The Incredibles",
  "Cars",
  "Ratatouille",
  "WALL-E",
  "Up",
  "Toy Story 3",
  "Cars 2",
  "Brave",
  "Monsters University",
  "Inside Out",
  "The Good Dinosaur",
  "Finding Dory",
  "Cars 3",
  "Coco",
  "Incredibles 2",
  "Toy Story 4",
  "Onward",
  "Soul",
  "Luca",
  "Turning Red",
  "Lightyear",
  "Elemental",
  "Barbie in the Nutcracker",
  "Barbie as Rapunzel",
  "Barbie of Swan Lake",
  "Barbie as The Princess and the Pauper",
  "Barbie: Fairy Secret",
  "Barbie Princess Charm School",
  "Barbie in A Mermaid Tale",
  "Barbie in A Mermaid Tale 2",
  "Barbie: Princess Power",
  "Barbie: Spy Squad",
  "Barbie and the Secret Door",
  "Barbie and the Diamond Castle",
  "Barbie as The Island Princess",
  "Barbie: A Fashion Fairytale",
  "Barbie and the Three Musketeers",
  "Barbie in Princess Power",
  "Barbie and Her Sisters in A Pony Tale",
  "Barbie: Dreamhouse Adventure",
  "Barbie: The Princess & The Popstar",
  "Barbie and the Secret Door",
  "Barbie in Rock 'N Royals",
  "Barbie and the Diamond Castle",
  "Barbie and the Magic of Pegasus",
  "Barbie and the Secret Door",
  "Barbie: Dreamtopia",
  "Barbie and the Twelve Dancing Princesses",
  "Barbie: Star Light Adventure",
  "Barbie in Princess Power",
  "Barbie in A Fashion Fairytale",
  "Barbie: Princess Charm School",
  "Barbie in the Pink Shoes",
  "Barbie: The Princess & The Pauper",
  "Barbie's Princess Adventure",
  "Barbie in a Christmas Carol",
  "Barbie and the Magic of Pegasus",
  "Barbie in Princess Power",
  "Twilight Sparkle",
  "Rainbow Dash",
  "Pinkie Pie",
  "Applejack",
  "Rarity",
  "Fluttershy",
  "Spike",
  "Princess Celestia",
  "Mickey Mouse",
  "Minnie Mouse",
  "Donald Duck",
  "Daisy Duck",
  "Goofy",
  "Pluto",
  "Clarabelle Cow",
  "Horace Horsecollar",
  "Chip",
  "Dale",
  "Winnie the Pooh",
  "Tigger",
  "Piglet",
  "Eeyore",
  "Christopher Robin",
  "Rabbit",
  "Owl",
  "Kanga",
  "Roo",
  "Heffalump",
  "Woozle",
  "Lumpy",
  "Tiglet",
  "The Backson",
  "The Gloomy Donkey",
  "Tigger's Family",
  "Heffalumps and Woozles",
  "Leonardo",
  "Michelangelo",
  "Donatello",
  "Raphael",
  "Splinter",
  "April O'Neil",
  "Casey Jones",
  "Shredder",
  "Krang",
  "Bebop",
  "Rocksteady",
  "Bob the Tomato",
  "Larry the Cucumber",
  "Junior Asparagus",
  "Petunia Rhubarb",
  "Mr. Lunt",
  "Pa Grape",
  "Archibald Asparagus",
  "Sweetpea",
  "Madame Blueberry",
  "Scallions",
  "The Grapes of Wrath",
  "The Pirates Who Don't Do Anything",
  "LarryBoy",
  "The Fib from Outer Space",
  "The Hairbrush Song",
  "King George",
  "Bob's Big Idea",
  "God Wants Me to Forgive Them?!",
  "Big Idea Productions",
  "The Gourds",
  "The Bumbleberry Pie",
  "Larry's High Silly Song",
  "Lenny the Lettuce",
  "The VeggieTales Theme Song",
  "Big Idea",
  "The Cheeseburger Song",
  "It's a Big Big World",
  "The Silly Songs with Larry",
  "The VeggieTales Movie",
  "The Thankfulness Song",
  "The Easter Carol",
  "LarryBoy and the Bad Apple",
  "Esther, the Girl Who Became Queen",
  "Silly Songs",
  "The Wizard of Ha's",
  "Jonah: A VeggieTales Movie",
  "The Ballad of Little Joe",
  "The League of Incredible Vegetables",
  "Tales of the Red Caboose",
  "Dave and the Giant Pickle",
  "God Made You Special",
  "Josh and the Big Wall",
  "The End of Silliness",
  "VeggieTales in the House",
  "Jonah's Journey",
  "Larry's Lagoon",
  "The Big Idea Workshop",
  "Bob and Larry's House",
  "The Secret of Joy",
  "Silly Songs with Bob and Larry",
  "The VeggieTales Live!",
  "The Water Buffalo Song",
  "The Song of the Cebu",
  "The Pirates Who Don't Do Anything",
  "The Hairbrush Song",
  "I Love My Lips",
  "The Belly Button Song",
  "Love My Duck",
  "The VeggieTales Theme Song",
  "The Grape Song",
  "The Dance of the Cucumber",
  "Larry's High Silly Song",
  "Silly Song with Larry",
  "The Fib from Outer Space",
  "The Cheeseburger Song",
  "The End of Silliness",
  "The Silly Song Christmas",
  "Where's My Hairbrush?",
  "Silly Songs with Larry (Live!)",
  "It's a Sillier Song",
  "Pizza Angel",
  "Silly Song Remix",
  "Despicable Me",
  "Despicable Me 2",
  "Minions",
  "The Secret Life of Pets",
  "Sing",
  "The Grinch",
  "Despicable Me 3",
  "Sing 2",
  "The Secret Life of Pets 2",
  "Minions: The Rise of Gru",
  "Hop",
  "The Lorax",
  "Secret Life of Pets",
  "Arthur",
  "Clifford the Big Red Dog",
  "Curious George",
  "Mister Rogers' Neighborhood",
  "Sesame Street",
  "Between the Lions",
  "Cyberchase",
  "Postcards from Buster",
  "Dragon Tales",
  "The Cat in the Hat Knows a Lot About That!",
  "Super Why!",
  "WordWorld",
  "Sid the Science Kid",
  "Elinor Wonders Why",
  "Nature Cat",
  "Curious George: A Very Monkey Christmas",
  "Daniel Tiger's Neighborhood",
  "Sesame Street's 50th Anniversary Celebration",
  "Clifford's Puppy Days",
  "The Magic School Bus Rides Again",
  "Splash and Bubbles",
  "Wild Kratts",
  "Peg + Cat",
  "Dinosaur Train",
  "Ready Jet Go!",
  "Odd Squad",
  "PBS Kids Logo",
  "Sesame Street: 123 Count with Me",
  "Sesame Street: Elmo's World",
  "Sesame Street: The Best of Elmo",
  "Barney & Friends",
  "WordGirl",
  "Curious George Goes to the Zoo"
];


                      
                  
              
          
      
  
// Function to update guessWord with a random string
function updateGuessWord() {
    // Get a random index
    
    if(category_ID == 0) {
        const randomIndex = Math.floor(Math.random() * geeky.length);
        // Set the text to a random string from the container
        guessWordElement.textContent = geeky[randomIndex];        
    }
    else if(category_ID == 1) {
        const randomIndex = Math.floor(Math.random() * kids_shows.length);
        guessWordElement.textContent = kids_shows[randomIndex];
    }

  }

  function nextCategory() {
    category_ID = (category_ID + 1) % NUM_CATEGORIES;
    console.log(category_ID);
    categoryElement.textContent = CATEGORIES[category_ID];
  }

// Attach the function to the button's click event
nextButton.addEventListener("click", updateGuessWord);
categoryElement.addEventListener("click", nextCategory);

